"""added RBA roles migration for CRUD functionalies

Revision ID: d523ff4c76f1
Revises: ec83e40d2437
Create Date: 2025-03-18 00:20:43.324505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd523ff4c76f1'
down_revision = 'ec83e40d2437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('project_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('new_priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('new_priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_history', schema=None) as batch_op:
        batch_op.drop_column('new_priority')
        batch_op.drop_column('old_priority')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('project_history', schema=None) as batch_op:
        batch_op.drop_column('new_priority')
        batch_op.drop_column('old_priority')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('archived_task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
